name: Frontend budtree_app

on:
  push:
    branches: 
    - 'feature/**'
  pull_request:
    branches:
    - 'master'
    - 'develop'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github 저장소의 최신 코드 내려받기
        uses: actions/checkout@v3

      - name: Docker hub에 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이지미 생성 및 Docker hub에 업로드
        run: |
          docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest .
          docker push ${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: EC2 서버에 SSH로 접속 해 기존 컨테이너 종료 및 최신 이미지를 받아 재배포 
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_KEY }}
          port: 22
          script: |
            docker stop budtree-front
            docker rm budtree-front
            docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
            docker run -d --name budtree-front -p 3000:3000 ${{ secrets.DOCKER_REPOSITORY }}:latest
            docker image prune -f